(source "var.c" (:std #f :compile #t :link #f)
        (var int x1)
        (var int x2 . 1)
        (var int x3 [1])
        (var int x4 [] . '{ 2 3 })
        (var int x5 [2] . '{ 4 5 })
        (var const int x6)
        (var const int x7 . 6)
        (var const int x8 [1])
        (var const int x9 [] . '{ 7 8 })
        (var const int x10 [2] . '{ 9 10 })
        (var int * p11)
        (var int * p12 . #'(aof x2))
        (var int * p13 [1])
        (var int * const p14)
        (var int * const p15 . #'(aof x2))
        (var int * const p16 [1])
        (var const int * const p17)
        (var const int * const p18 . #'(aof x2))
        (var const int * const p19 [] . '{ (aof x2) (aof x7) })
        (var char s20 [3][4])
        (var char s21 [][5] . '{ "Hello" "World" })
        (var char * s22 [1])
        (var char * s23 [] . '{ "John" "Doe" })
        (var char ** s24)
        (var char ** s25 . s23)
        (var const char s26 [6][7])
        (var const char s27 [][4] . '{ "ABCD" "EFG" })
        (var const char * s28 [1])
        (var const char * s29 [] . '{ "HIJK" "LMNOP" })
        (var const char ** s30)
        (var const char ** s31 . s29)
        (var const char * const s32 [1])
        (var const char * const s33 [] . '{ "WX" "YZ" })
        (var const char ** const s34)
        (var const char ** const s35 . s29))
