(in-package :lcc)

(defvar *lcc-std* "#ifndef __LCC_STD__
#define __LCC_STD__
#define __lcc_is_same_type(a, b)  __builtin_types_compatible_p(typeof(a), typeof(b))
#define __lcc_is_pointer_or_array(p)  (__builtin_classify_type(p) == 5)
#define __lcc_decay(p)  (&*__builtin_choose_expr(__lcc_is_pointer_or_array(p), p, NULL))
#define __lcc_is_pointer(p)  __lcc_is_same_type(p, __lcc_decay(p))
#define __lcc_pointout(v) (__builtin_choose_expr(__lcc_is_pointer(v), v, &v))
#define __lcc_receiver(s, m) typeof(*__lcc_pointout(s))##_info __lcc_ m
#endif // __LCC_STD__~%")

(defun specify-target (target)
  (let* ((name    (nth 1 target))
	     (args    (nth 2 target))
	     (clauses (nthcdr 3 target))
	     (target-specifier (make-specifier name '|@TARGET| nil nil nil nil nil nil args)))
    (format t "lcc: specifying target ~A~%" name)
    (unless (zerop (mod (length args) 2)) (error (format nil "wrong target features ~A" name)))
    (let ((attributes '()))
      (dolist (clause clauses)
	    (if (consp clause)
	        (let ((construct (car clause)))
	          (cond ((find (char (symbol-name construct) 0) "@#")
		             (add-inner (specify-preprocessor clause attributes) target-specifier)
		             (setq attributes '()))
		            ((key-eq construct '|static|)   (push clause attributes))
		            ((key-eq construct '|decl|)     (push clause attributes))
		            ((key-eq construct '|inline|)   (push clause attributes))
		            ((key-eq construct '|register|) (push clause attributes))
		            ((key-eq construct '|auto|)     (push clause attributes))
		            ((key-eq construct '|extern|)   (push clause attributes))
		            ((key-eq construct '|resolve|)  (push clause attributes))
		            ((key-eq construct '|include|)
		             (add-inner (specify-include  clause attributes) target-specifier)
		             (setq attributes '()))
		            ((key-eq construct '|guard|)
		             (add-inner (specify-guard    clause attributes) target-specifier)
		             (setq attributes '()))
		            ((key-eq construct '|var|)
		             (add-inner (specify-variable clause attributes) target-specifier)
		             (setq attributes '()))
		            ((key-eq construct '|func|)
		             (add-inner (specify-function clause attributes) target-specifier)
		             (setq attributes '()))
		            ((key-eq construct '|method|)
		             (add-inner (specify-function clause attributes) target-specifier)
		             (setq attributes '()))
		            ((key-eq construct '|enum|)
		             (add-inner (specify-enum     clause attributes) target-specifier)
		             (setq attributes '()))
		            ((key-eq construct '|struct|)
		             (add-inner (specify-struct   clause attributes) target-specifier)
		             (setq attributes '()))
		            ((key-eq construct '|union|)
		             (add-inner (specify-union    clause attributes) target-specifier)
		             (setq attributes '()))
		            ((key-eq construct '|typedef|)
		             (add-inner (specify-typedef  clause attributes) target-specifier)
		             (setq attributes '()))
		            (t (error (format nil "unknown clause ~A in target ~A" construct name)))))
	        (error (format nil "syntax error ~A" clause))))
      target-specifier)))

(defun compile-target (file spec globals stdout stderr dump header)
  (let ((args (attrs spec)))
    (if (stringp file)
        (progn
          (ensure-directories-exist file)
          (setq *output*
		        (open file
			          :direction :output
			          :if-does-not-exist :create
			          :if-exists :supersede)))
        (error (format t "target should be a file path")))
    (if dump (format t "lcc: resolving target ~A~%" file) (format t "lcc: compiling target ~A~%" file))
    (unwind-protect
         (handler-case 
	         (progn
               (funcall *line-num* 0 :reset 1)
               (funcall *col-num* 0 :reset 1)
	           ;; (output *lcc-std*)
	           (dotimes (i (length args))
	             (when (zerop (mod i 2))
	               (when (key-eq (nth i args) ':|std|)
		             (let ((custom (nth (+ i 1) args)))
		               (when (key-eq custom '|true|)
                         (set-ast-line (output "~&#include ")) (set-ast-line (output "<stdio.h>~%"))
                         (set-ast-line (output "~&#include ")) (set-ast-line (output "<stddef.h>~%"))
                         (set-ast-line (output "~&#include ")) (set-ast-line (output "<stdint.h>~%"))
                         (set-ast-line (output "~&#include ")) (set-ast-line (output "<stdlib.h>~%"))
                         (set-ast-line (output "~&#include ")) (set-ast-line (output "<stdbool.h>~%"))
                         (set-ast-line (output "~&#include ")) (set-ast-line (output "<string.h>~%")))))))
	           (maphash #'(lambda (in-name in-spec)
		                    (case (construct in-spec)
			                  ('|@PREPROC|  (compile-preprocessor in-spec 0 globals))
			                  ('|@INCLUDE|  (compile-include      in-spec 0 globals))
			                  ('|@TYPEDEF|  (compile-typedef      in-spec 0 globals))
			                  ('|@VAR|      (compile-variable     in-spec 0 globals))
			                  ('|@FUNC|     (compile-function     in-spec 0 globals))
			                  ('|@METHOD|   (compile-function     in-spec 0 globals))
			                  ('|@ENUM|     (compile-enum         in-spec 0 globals))
			                  ('|@STRUCT|   (compile-struct       in-spec 0 globals))
			                  ('|@UNION|    (compile-union        in-spec 0 globals))
			                  ('|@GUARD|    (compile-guard        in-spec 0 globals))
			                  (otherwise
                               (error (format nil "unknown construct ~A in ~A" (construct in-spec) in-name)))))
		                (inners spec))
	           (close *output*)
               (when header (return-from compile-target t))
               (let ((is-compiled nil))
	             (dotimes (i (length args))
	               (when (zerop (mod i 2))
	                 (when (key-eq (nth i args) ':|compile|)
		               (let* ((dumper    (getf *configs* 'dumper))
                              (command   (getf *configs* 'compiler))
		                      (program   (car command))
		                      (arguments (cdr command))
		                      (custom    (nth (+ i 1) args)))
                         (if (or (key-eq custom '|true|) (stringp custom))
                             (progn
		                       (if (key-eq custom '|true|)
                                   (setq custom (list "-c" file))
                                   (if (stringp custom)
                                       (setq custom (str:split " " custom))
                                       (setq custom (append custom (list "-c" file)))))
                               (let ((cwd       (uiop/os:getcwd))
                                     (args      `(,program ,@arguments ,@custom))
                                     (dump-args `(,program ,@arguments ,@dumper ,@custom)))
                                 (setq args      (replace-args< `(("{$CWD}" ,cwd)) args))
                                 (setq dump-args (replace-args< `(("{$CWD}" ,cwd)) dump-args))
                                 ;; (display "ARGS" args)
                                 (if dump
                                     (uiop:run-program dump-args :input nil :output stdout :error-output stderr)
		                             (uiop:run-program args :input nil :output stdout :error-output stderr))))
                             (error (format nil "invalid :compile value, required a custom command or #t"))))
                       (setq is-compiled t))
	                 (when (key-eq (nth i args) ':|link|)
                       (if is-compiled
		                   (let* ((command   (getf *configs* 'linker))
		                          (program   (car command))
		                          (arguments (cdr command))
		                          (custom    (nth (+ i 1) args)))
		                     (unless (key-eq custom '|false|)
                               (if (key-eq custom '|true|)
                                   (setq custom (list file "-o" "main"))
                                   (when (stringp custom)
                                     (setq custom (str:split " " custom))))
                               (let ((cwd       (uiop/os:getcwd))
                                     (args      `(,program ,@arguments ,@custom)))
                                 (setq args (replace-args< `(("{$CWD}" ,cwd)) args))
                                 ;; (display cwd "ARGS" args)
		                         (uiop:run-program args :input nil :output stdout :error-output stderr))))
                           (error (format nil ":link without :compile, compilation is required"))))))))
           (uiop/run-program:subprocess-error (e) (format t "~A~%" e)))
      (progn
	    (close *output*)))))
